export default {
    area: {
        "type-id": null,
        disambiguation: "",
        id: "489ce91b-6658-3307-9877-795b68554c98",
        type: null,
        "sort-name": "United States",
        name: "United States",
        "iso-3166-1-codes": ["US"],
    },
    country: "US",
    relations: [
        {
            url: {
                resource: "https://www.allmusic.com/artist/mn0000357406",
                id: "4a425cd3-641d-409c-a282-2334935bf1bd",
            },
            type: "allmusic",
            "attribute-ids": {},
            "target-credit": "",
            "type-id": "6b3e3c85-0002-4f34-aca6-80ace0d7e846",
            begin: null,
            "attribute-values": {},
            ended: false,
            direction: "forward",
            end: null,
            "target-type": "url",
            "source-credit": "",
            attributes: [],
        },
        {
            url: {
                id: "627ce98c-0eef-41c7-b28f-cc3387b98aab",
                resource:
                    "https://www.bbc.co.uk/music/artists/5b11f4ce-a62d-471e-81fc-a69a8278c7da",
            },
            type: "BBC Music page",
            "source-credit": "",
            end: "2020-11-19",
            "target-type": "url",
            attributes: [],
            ended: true,
            "attribute-values": {},
            "attribute-ids": {},
            "target-credit": "",
            begin: null,
            "type-id": "d028a975-000c-4525-9333-d3c8425e4b54",
            direction: "forward",
        },
        {
            type: "discography page",
            url: {
                resource:
                    "http://www.livenirvana.com/bootography/listing85a9.html?listingquery=all",
                id: "73a6779b-8aaa-42ff-9833-e550ad974be4",
            },
            direction: "forward",
            begin: null,
            "type-id": "4fb0eeec-a6eb-4ae3-ad52-b55765b94e8f",
            "target-credit": "",
            "attribute-ids": {},
            "attribute-values": {},
            ended: false,
            attributes: [],
            "target-type": "url",
            end: null,
            "source-credit": "",
        },
        {
            url: {
                id: "aa2f9928-f2d0-4ce3-9714-af7566b9df94",
                resource:
                    "http://www.livenirvana.com/digitalnirvana/discography/index.html",
            },
            type: "discography page",
            "attribute-values": {},
            ended: false,
            "attribute-ids": {},
            "target-credit": "",
            begin: null,
            "type-id": "4fb0eeec-a6eb-4ae3-ad52-b55765b94e8f",
            direction: "forward",
            "source-credit": "",
            end: null,
            "target-type": "url",
            attributes: [],
        },
        {
            attributes: [],
            "source-credit": "",
            end: null,
            "target-type": "url",
            direction: "forward",
            "attribute-values": {},
            ended: false,
            "target-credit": "",
            "attribute-ids": {},
            begin: null,
            "type-id": "4fb0eeec-a6eb-4ae3-ad52-b55765b94e8f",
            type: "discography page",
            url: {
                resource: "http://www.nirvanaarchive.com/",
                id: "d0498330-0679-4174-a145-273dd974e09e",
            },
        },
        {
            direction: "forward",
            ended: false,
            "attribute-values": {},
            "target-credit": "",
            "attribute-ids": {},
            begin: null,
            "type-id": "04a5b104-a4c2-4bac-99a1-7b837c37d9e4",
            attributes: [],
            "source-credit": "",
            end: null,
            "target-type": "url",
            type: "discogs",
            url: {
                id: "81846eca-af41-43d0-bcae-b62dbf5cfa2f",
                resource: "https://www.discogs.com/artist/125246",
            },
        },
        {
            attributes: [],
            "target-type": "url",
            end: null,
            "source-credit": "",
            direction: "forward",
            "type-id": "f484f897-81cc-406e-96f9-cd799a04ee24",
            begin: null,
            "attribute-ids": {},
            "target-credit": "",
            ended: false,
            "attribute-values": {},
            type: "fanpage",
            url: {
                id: "74c7fc4f-cb3d-45ef-9c83-f7a1061f0272",
                resource: "http://www.livenirvana.com/",
            },
        },
        {
            begin: null,
            "type-id": "f484f897-81cc-406e-96f9-cd799a04ee24",
            "attribute-ids": {},
            "target-credit": "",
            "attribute-values": {},
            ended: false,
            direction: "forward",
            "target-type": "url",
            end: null,
            "source-credit": "",
            attributes: [],
            url: {
                resource: "http://www.nirvanaclub.com/",
                id: "e42476ce-e923-498e-8e98-d11ae200aebb",
            },
            type: "fanpage",
        },
        {
            type: "free streaming",
            url: {
                resource:
                    "https://open.spotify.com/artist/6olE6TJLqED3rqDCT0FyPh",
                id: "f6a499eb-5959-4861-95f1-13caec960006",
            },
            attributes: [],
            end: null,
            "target-type": "url",
            "source-credit": "",
            direction: "forward",
            "target-credit": "",
            "attribute-ids": {},
            begin: null,
            "type-id": "769085a1-c2f7-4c24-a532-2375a77693bd",
            "attribute-values": {},
            ended: false,
        },
        {
            type: "free streaming",
            url: {
                resource: "https://www.deezer.com/artist/415",
                id: "05fd4bd7-b7c8-44f3-afdd-0f6b6b0b6092",
            },
            direction: "forward",
            begin: null,
            "type-id": "769085a1-c2f7-4c24-a532-2375a77693bd",
            "target-credit": "",
            "attribute-ids": {},
            ended: false,
            "attribute-values": {},
            attributes: [],
            "target-type": "url",
            end: null,
            "source-credit": "",
        },
        {
            url: {
                id: "c29fa499-8e33-455a-aaa0-d93ea088c55f",
                resource: "http://www.pandora.com/nirvana",
            },
            type: "free streaming",
            "source-credit": "",
            end: null,
            "target-type": "url",
            attributes: [],
            ended: false,
            "attribute-values": {},
            "target-credit": "",
            "attribute-ids": {},
            begin: null,
            "type-id": "769085a1-c2f7-4c24-a532-2375a77693bd",
            direction: "forward",
        },
        {
            type: "image",
            url: {
                id: "88867281-e540-4b37-9fce-870dda1bfd8b",
                resource:
                    "https://commons.wikimedia.org/wiki/File:Nirvana_around_1992.jpg",
            },
            direction: "forward",
            ended: false,
            "attribute-values": {},
            begin: null,
            "type-id": "221132e9-e30e-43f2-a741-15afc4c5fa7c",
            "target-credit": "",
            "attribute-ids": {},
            attributes: [],
            "source-credit": "",
            "target-type": "url",
            end: null,
        },
        {
            ended: false,
            "attribute-values": {},
            begin: null,
            "type-id": "94c8b0cc-4477-4106-932c-da60e63de61c",
            "target-credit": "",
            "attribute-ids": {},
            direction: "forward",
            "source-credit": "",
            "target-type": "url",
            end: null,
            attributes: [],
            url: {
                id: "85229dcd-cc79-4ce8-a3be-4b0539e9148a",
                resource: "https://www.imdb.com/name/nm1110321/",
            },
            type: "IMDb",
        },
        {
            type: "last.fm",
            url: {
                id: "36dc918b-2a58-4d31-9ccd-10af003e7386",
                resource: "https://www.last.fm/music/Nirvana",
            },
            direction: "forward",
            "type-id": "08db8098-c0df-4b78-82c3-c8697b4bba7f",
            begin: null,
            "attribute-ids": {},
            "target-credit": "",
            "attribute-values": {},
            ended: false,
            attributes: [],
            "target-type": "url",
            end: null,
            "source-credit": "",
        },
        {
            attributes: [],
            "source-credit": "",
            "target-type": "url",
            end: null,
            direction: "forward",
            ended: false,
            "attribute-values": {},
            "type-id": "e4d73442-3762-45a8-905c-401da65544ed",
            begin: null,
            "target-credit": "",
            "attribute-ids": {},
            type: "lyrics",
            url: {
                resource: "http://muzikum.eu/en/122-4216/nirvana/lyrics.html",
                id: "740505c7-3a30-4482-8ca6-10183b37d308",
            },
        },
        {
            attributes: [],
            "source-credit": "",
            end: null,
            "target-type": "url",
            direction: "forward",
            "attribute-values": {},
            ended: false,
            "target-credit": "",
            "attribute-ids": {},
            "type-id": "e4d73442-3762-45a8-905c-401da65544ed",
            begin: null,
            type: "lyrics",
            url: {
                id: "eb2efdf0-05cf-4ea8-bc00-b1b0d2bcdcfb",
                resource: "https://genius.com/artists/Nirvana",
            },
        },
        {
            attributes: [],
            "source-credit": "",
            "target-type": "url",
            end: null,
            direction: "forward",
            ended: false,
            "attribute-values": {},
            begin: null,
            "type-id": "e4d73442-3762-45a8-905c-401da65544ed",
            "target-credit": "",
            "attribute-ids": {},
            type: "lyrics",
            url: {
                resource: "https://www.musixmatch.com/artist/Nirvana",
                id: "b7863533-0c1f-405a-9ca0-cd5c09f94efd",
            },
        },
        {
            url: {
                resource: "https://myspace.com/nirvana",
                id: "706cb178-5d5c-49e0-a07f-149751b94043",
            },
            type: "myspace",
            "attribute-values": {},
            ended: false,
            begin: null,
            "type-id": "bac47923-ecde-4b59-822e-d08f0cd10156",
            "attribute-ids": {},
            "target-credit": "",
            direction: "forward",
            "source-credit": "",
            "target-type": "url",
            end: null,
            attributes: [],
        },
        {
            url: {
                resource: "http://www.nirvana.com/",
                id: "4347ffe2-82ec-4059-9520-6a1a3f73a304",
            },
            type: "official homepage",
            ended: false,
            "attribute-values": {},
            "attribute-ids": {},
            "target-credit": "",
            "type-id": "fe33d22f-c3b0-4d68-bd53-a856badf2b15",
            begin: null,
            direction: "forward",
            "source-credit": "",
            end: null,
            "target-type": "url",
            attributes: [],
        },
        {
            type: "other databases",
            url: {
                resource: "http://d-nb.info/gnd/10295339-9",
                id: "88a3f586-d383-4cd8-9458-f48512533799",
            },
            attributes: [],
            "target-type": "url",
            end: null,
            "source-credit": "",
            direction: "forward",
            begin: null,
            "type-id": "d94fb61c-fa20-4e3c-a19a-71a949fb2c55",
            "attribute-ids": {},
            "target-credit": "",
            "attribute-values": {},
            ended: false,
        },
        {
            url: {
                id: "222144c5-b46d-4d67-9f56-e9fb654e2e86",
                resource: "http://id.loc.gov/authorities/names/n92011111",
            },
            type: "other databases",
            ended: false,
            "attribute-values": {},
            "target-credit": "",
            "attribute-ids": {},
            "type-id": "d94fb61c-fa20-4e3c-a19a-71a949fb2c55",
            begin: null,
            direction: "forward",
            "source-credit": "",
            end: null,
            "target-type": "url",
            attributes: [],
        },
        {
            "attribute-values": {},
            ended: false,
            begin: null,
            "type-id": "d94fb61c-fa20-4e3c-a19a-71a949fb2c55",
            "target-credit": "",
            "attribute-ids": {},
            direction: "forward",
            "source-credit": "",
            "target-type": "url",
            end: null,
            attributes: [],
            url: {
                resource: "http://musicmoz.org/Bands_and_Artists/N/Nirvana/",
                id: "21daaa31-4c41-4fc9-b07d-e77b3f01d3e6",
            },
            type: "other databases",
        },
        {
            type: "other databases",
            url: {
                resource: "https://catalogue.bnf.fr/ark:/12148/cb13944446b",
                id: "96d41441-df74-4dda-8a0f-c99462b22a7c",
            },
            direction: "forward",
            ended: false,
            "attribute-values": {},
            "type-id": "d94fb61c-fa20-4e3c-a19a-71a949fb2c55",
            begin: null,
            "target-credit": "",
            "attribute-ids": {},
            attributes: [],
            "source-credit": "",
            "target-type": "url",
            end: null,
        },
        {
            type: "other databases",
            url: {
                id: "984aef79-06a7-471f-96ef-0f2dd1fd20de",
                resource: "https://imvdb.com/n/nirvana",
            },
            direction: "forward",
            "attribute-ids": {},
            "target-credit": "",
            begin: null,
            "type-id": "d94fb61c-fa20-4e3c-a19a-71a949fb2c55",
            "attribute-values": {},
            ended: false,
            attributes: [],
            end: null,
            "target-type": "url",
            "source-credit": "",
        },
        {
            type: "other databases",
            url: {
                id: "1631d12d-9c1f-4899-a2d4-f54ffe615ca1",
                resource: "https://nla.gov.au/nla.party-1179730",
            },
            attributes: [],
            end: null,
            "target-type": "url",
            "source-credit": "",
            direction: "forward",
            "target-credit": "",
            "attribute-ids": {},
            "type-id": "d94fb61c-fa20-4e3c-a19a-71a949fb2c55",
            begin: null,
            "attribute-values": {},
            ended: false,
        },
        {
            type: "other databases",
            url: {
                resource: "https://rateyourmusic.com/artist/nirvana",
                id: "07a468c6-3ceb-4e44-b0b9-f46cca1151dc",
            },
            direction: "forward",
            "attribute-values": {},
            ended: false,
            "attribute-ids": {},
            "target-credit": "",
            "type-id": "d94fb61c-fa20-4e3c-a19a-71a949fb2c55",
            begin: null,
            attributes: [],
            "source-credit": "",
            end: null,
            "target-type": "url",
        },
        {
            url: {
                resource: "https://www.livefans.jp/artists/21724",
                id: "059071fd-b921-4ee4-a031-de11e2c8d4d3",
            },
            type: "other databases",
            "source-credit": "",
            "target-type": "url",
            end: null,
            attributes: [],
            "attribute-values": {},
            ended: false,
            "type-id": "d94fb61c-fa20-4e3c-a19a-71a949fb2c55",
            begin: null,
            "attribute-ids": {},
            "target-credit": "",
            direction: "forward",
        },
        {
            type: "other databases",
            url: {
                resource: "https://www.musik-sammler.de/artist/nirvana/",
                id: "902a6503-ed52-4207-ae6e-f1a64dc53888",
            },
            attributes: [],
            "source-credit": "",
            end: null,
            "target-type": "url",
            direction: "forward",
            ended: false,
            "attribute-values": {},
            "target-credit": "",
            "attribute-ids": {},
            begin: null,
            "type-id": "d94fb61c-fa20-4e3c-a19a-71a949fb2c55",
        },
        {
            attributes: [],
            "source-credit": "",
            "target-type": "url",
            end: null,
            direction: "forward",
            ended: false,
            "attribute-values": {},
            "type-id": "d94fb61c-fa20-4e3c-a19a-71a949fb2c55",
            begin: null,
            "target-credit": "",
            "attribute-ids": {},
            type: "other databases",
            url: {
                resource: "https://www.spirit-of-metal.com/en/band/Nirvana",
                id: "dc807420-0cd6-4c4f-8c2e-0c70cbe37f64",
            },
        },
        {
            direction: "forward",
            begin: null,
            "type-id": "d94fb61c-fa20-4e3c-a19a-71a949fb2c55",
            "attribute-ids": {},
            "target-credit": "",
            "attribute-values": {},
            ended: false,
            attributes: [],
            "target-type": "url",
            end: null,
            "source-credit": "",
            type: "other databases",
            url: {
                resource: "https://www.whosampled.com/Nirvana/",
                id: "805e0346-cdfb-4eae-a8c4-f27937288cda",
            },
        },
        {
            url: {
                resource: "http://www.45cat.com/artist/nirvana-us",
                id: "856db026-ed62-4d4b-b91e-301ab15bc89f",
            },
            type: "other databases",
            "source-credit": "",
            "target-type": "url",
            end: null,
            attributes: [],
            ended: false,
            "attribute-values": {},
            begin: null,
            "type-id": "d94fb61c-fa20-4e3c-a19a-71a949fb2c55",
            "target-credit": "",
            "attribute-ids": {},
            direction: "forward",
        },
        {
            type: "other databases",
            url: {
                id: "2127a8c5-befb-401c-a6f0-057b4f4a4581",
                resource: "http://www.worldcat.org/wcidentities/lccn-n92-11111",
            },
            attributes: [],
            end: null,
            "target-type": "url",
            "source-credit": "",
            direction: "forward",
            "target-credit": "",
            "attribute-ids": {},
            "type-id": "d94fb61c-fa20-4e3c-a19a-71a949fb2c55",
            begin: null,
            ended: false,
            "attribute-values": {},
        },
        {
            "type-id": "f8319a2f-f824-4617-81c8-be6560b3b203",
            begin: null,
            "target-credit": "",
            "attribute-ids": {},
            "attribute-values": {},
            ended: true,
            direction: "forward",
            "target-type": "url",
            end: "2020-10-12",
            "source-credit": "",
            attributes: [],
            url: {
                id: "adb16d0b-c38d-471c-b3da-4f715267f620",
                resource:
                    "https://play.google.com/store/music/artist?id=Apyli2ev5del3s42qsjpnmqwuue",
            },
            type: "purchase for download",
        },
        {
            attributes: [],
            "target-type": "url",
            end: null,
            "source-credit": "",
            direction: "forward",
            begin: null,
            "type-id": "f8319a2f-f824-4617-81c8-be6560b3b203",
            "attribute-ids": {},
            "target-credit": "",
            ended: false,
            "attribute-values": {},
            type: "purchase for download",
            url: {
                id: "9fc44b9f-8ca9-4079-952f-fcd8a2976dbf",
                resource: "https://itunes.apple.com/us/artist/id112018",
            },
        },
        {
            ended: false,
            "attribute-values": {},
            "type-id": "f8319a2f-f824-4617-81c8-be6560b3b203",
            begin: null,
            "attribute-ids": {},
            "target-credit": "",
            direction: "forward",
            "source-credit": "",
            "target-type": "url",
            end: null,
            attributes: [],
            url: {
                id: "d1f77e8a-8483-4add-aaf0-ad362795872c",
                resource: "https://us.7digital.com/artist/nirvana",
            },
            type: "purchase for download",
        },
        {
            direction: "forward",
            "attribute-values": {},
            ended: false,
            "attribute-ids": {},
            "target-credit": "",
            begin: null,
            "type-id": "f8319a2f-f824-4617-81c8-be6560b3b203",
            attributes: [],
            "source-credit": "",
            end: null,
            "target-type": "url",
            type: "purchase for download",
            url: {
                id: "5b9a913e-3024-4754-bd0b-abafcfa098d8",
                resource:
                    "https://www.junodownload.com/artists/Nirvana/releases/",
            },
        },
        {
            url: {
                id: "1a3728c4-3e23-49c7-916e-02b02af4d6b0",
                resource:
                    "https://www.qobuz.com/gb-en/interpreter/nirvana/download-streaming-albums",
            },
            type: "purchase for download",
            "attribute-values": {},
            ended: false,
            "target-credit": "",
            "attribute-ids": {},
            begin: null,
            "type-id": "f8319a2f-f824-4617-81c8-be6560b3b203",
            direction: "forward",
            "source-credit": "",
            end: null,
            "target-type": "url",
            attributes: [],
        },
        {
            end: null,
            "target-type": "url",
            "source-credit": "",
            attributes: [],
            "target-credit": "",
            "attribute-ids": {},
            "type-id": "611b1862-67af-4253-a64f-34adba305d1d",
            begin: null,
            ended: false,
            "attribute-values": {},
            direction: "forward",
            url: {
                resource: "https://www.cdjapan.co.jp/person/700298036",
                id: "7be83207-f706-435b-81f2-5f57f109e652",
            },
            type: "purchase for mail-order",
        },
        {
            "target-type": "url",
            end: "2018-06-30",
            "source-credit": "",
            attributes: [],
            begin: null,
            "type-id": "b6f02157-a9d3-4f24-9057-0675b2dbc581",
            "target-credit": "",
            "attribute-ids": {},
            ended: true,
            "attribute-values": {},
            direction: "forward",
            url: {
                id: "61139a11-0318-481d-b305-bf569e400e50",
                resource: "http://www.purevolume.com/Nirvana109A",
            },
            type: "purevolume",
        },
        {
            attributes: [],
            "source-credit": "",
            "target-type": "url",
            end: null,
            direction: "forward",
            ended: false,
            "attribute-values": {},
            "type-id": "79c5b84d-a206-4f4c-9832-78c028c312c3",
            begin: null,
            "target-credit": "",
            "attribute-ids": {},
            type: "secondhandsongs",
            url: {
                id: "5f33ae58-aa56-40bd-ad14-ab7db9b3d3fd",
                resource: "https://secondhandsongs.com/artist/169",
            },
        },
        {
            url: {
                id: "47616077-74cb-47c6-8bd4-cf34753a9af0",
                resource:
                    "https://www.setlist.fm/setlists/nirvana-7bd69ee8.html",
            },
            type: "setlistfm",
            "source-credit": "",
            "target-type": "url",
            end: null,
            attributes: [],
            ended: false,
            "attribute-values": {},
            "type-id": "bf5d0d5e-27a1-4e94-9df7-3cdc67b3b207",
            begin: null,
            "target-credit": "",
            "attribute-ids": {},
            direction: "forward",
        },
        {
            url: {
                id: "f5cfd704-b99a-45fc-9aed-8747257cad03",
                resource: "https://twitter.com/Nirvana",
            },
            type: "social network",
            end: null,
            "target-type": "url",
            "source-credit": "",
            attributes: [],
            "attribute-ids": {},
            "target-credit": "",
            "type-id": "99429741-f3f6-484b-84f8-23af51991770",
            begin: null,
            "attribute-values": {},
            ended: false,
            direction: "forward",
        },
        {
            "attribute-values": {},
            ended: false,
            "type-id": "99429741-f3f6-484b-84f8-23af51991770",
            begin: null,
            "target-credit": "",
            "attribute-ids": {},
            direction: "forward",
            "source-credit": "",
            "target-type": "url",
            end: null,
            attributes: [],
            url: {
                id: "a9cec2d1-0544-4dc9-a4b2-640751654573",
                resource: "https://www.facebook.com/Nirvana",
            },
            type: "social network",
        },
        {
            url: {
                resource: "https://soundcloud.com/nirvana",
                id: "14c6ec03-4bd8-4f12-bfef-f2450746adab",
            },
            type: "soundcloud",
            "source-credit": "",
            end: null,
            "target-type": "url",
            attributes: [],
            "attribute-values": {},
            ended: false,
            "attribute-ids": {},
            "target-credit": "",
            "type-id": "89e4a949-0976-440d-bda1-5f772c1e5710",
            begin: null,
            direction: "forward",
        },
        {
            attributes: [],
            "target-type": "url",
            end: null,
            "source-credit": "",
            direction: "forward",
            "type-id": "63cc5d1f-f096-4c94-a43f-ecb32ea94161",
            begin: null,
            "attribute-ids": {},
            "target-credit": "",
            ended: false,
            "attribute-values": {},
            type: "streaming",
            url: {
                id: "a39c4986-e579-4c23-85a4-4137a5d0e63e",
                resource: "https://listen.tidal.com/artist/19368",
            },
        },
        {
            attributes: [],
            "source-credit": "",
            "target-type": "url",
            end: null,
            direction: "forward",
            "attribute-values": {},
            ended: false,
            begin: null,
            "type-id": "63cc5d1f-f096-4c94-a43f-ecb32ea94161",
            "target-credit": "",
            "attribute-ids": {},
            type: "streaming",
            url: {
                id: "0d12ebdb-3408-4ef7-ae8f-ef1d88c378af",
                resource: "https://music.amazon.com/artists/B001DTD5NQ",
            },
        },
        {
            attributes: [],
            "source-credit": "",
            "target-type": "url",
            end: null,
            direction: "forward",
            ended: false,
            "attribute-values": {},
            "type-id": "63cc5d1f-f096-4c94-a43f-ecb32ea94161",
            begin: null,
            "attribute-ids": {},
            "target-credit": "",
            type: "streaming",
            url: {
                resource: "https://music.apple.com/us/artist/112018",
                id: "930d6ea3-5ce7-4588-8edf-7ef465acca0c",
            },
        },
        {
            url: {
                id: "821d7ca7-1b18-4df9-8cdd-db892caf2cc7",
                resource: "https://us.napster.com/artist/nirvana",
            },
            type: "streaming",
            "attribute-ids": {},
            "target-credit": "",
            begin: null,
            "type-id": "63cc5d1f-f096-4c94-a43f-ecb32ea94161",
            ended: false,
            "attribute-values": {},
            direction: "forward",
            end: null,
            "target-type": "url",
            "source-credit": "",
            attributes: [],
        },
        {
            direction: "forward",
            ended: false,
            "attribute-values": {},
            begin: null,
            "type-id": "e8571dcc-35d4-4e91-a577-a3382fd84460",
            "attribute-ids": {},
            "target-credit": "",
            attributes: [],
            "source-credit": "",
            "target-type": "url",
            end: null,
            type: "VIAF",
            url: {
                resource: "http://viaf.org/viaf/138573893",
                id: "421a959a-c50f-4a52-99e4-3c603dd37145",
            },
        },
        {
            type: "wikidata",
            url: {
                id: "1221730c-3a48-49fa-8001-beaa6e93c892",
                resource: "https://www.wikidata.org/wiki/Q11649",
            },
            attributes: [],
            "source-credit": "",
            end: null,
            "target-type": "url",
            direction: "forward",
            ended: false,
            "attribute-values": {},
            "target-credit": "",
            "attribute-ids": {},
            begin: null,
            "type-id": "689870a4-a1e4-4912-b17f-7b2664215698",
        },
        {
            attributes: [],
            "target-type": "url",
            end: null,
            "source-credit": "",
            direction: "forward",
            begin: null,
            "type-id": "6a540e5b-58c6-4192-b6ba-dbc71ec8fcf0",
            "attribute-ids": {},
            "target-credit": "",
            "attribute-values": {},
            ended: false,
            type: "youtube",
            url: {
                resource: "https://www.youtube.com/user/NirvanaVEVO",
                id: "c8d415be-b993-4ade-bd28-d3ab4806fcbd",
            },
        },
    ],
    id: "5b11f4ce-a62d-471e-81fc-a69a8278c7da",
    type: "Group",
    "life-span": {
        begin: "1988-01",
        end: "1994-04-05",
        ended: true,
    },
    disambiguation: "90s US grunge band",
    "begin-area": {
        "sort-name": "Aberdeen",
        "type-id": null,
        name: "Aberdeen",
        disambiguation: "",
        id: "a640b45c-c173-49b1-8030-973603e895b5",
        type: null,
    },
    name: "Nirvana",
    "sort-name": "Nirvana",
    "release-groups": [
        {
            "primary-type-id": "f529b476-6e62-324f-b0aa-1f3e33d313fc",
            "secondary-types": [],
            disambiguation: "",
            "primary-type": "Album",
            "first-release-date": "1989-06-01",
            id: "f1afec0b-26dd-3db5-9aa1-c91229a74a24",
            title: "Bleach",
            "secondary-type-ids": [],
        },
        {
            "primary-type-id": "f529b476-6e62-324f-b0aa-1f3e33d313fc",
            "secondary-types": [],
            "secondary-type-ids": [],
            title: "Nevermind",
            id: "1b022e01-4da6-387b-8658-8678046e4cef",
            "primary-type": "Album",
            disambiguation: "",
            "first-release-date": "1991-09-24",
        },
        {
            "primary-type-id": "f529b476-6e62-324f-b0aa-1f3e33d313fc",
            "secondary-types": [],
            disambiguation: "",
            "primary-type": "Album",
            "first-release-date": "1993-09-21",
            id: "2a0981fb-9593-3019-864b-ce934d97a16e",
            title: "In Utero",
            "secondary-type-ids": [],
        },
        {
            title: "Incesticide",
            "secondary-type-ids": ["dd2a21e1-0c00-3729-a7a0-de60b84eb5d1"],
            "primary-type": "Album",
            disambiguation: "",
            "first-release-date": "1992-12-14",
            id: "01cf1391-141b-3c87-8650-45ade6e59070",
            "primary-type-id": "f529b476-6e62-324f-b0aa-1f3e33d313fc",
            "secondary-types": ["Compilation"],
        },
        {
            "secondary-types": ["Compilation"],
            "primary-type-id": "f529b476-6e62-324f-b0aa-1f3e33d313fc",
            id: "5ab32af4-c62e-3cbf-aa8c-c761581d3b94",
            "first-release-date": "2002-10-18",
            disambiguation: "",
            "primary-type": "Album",
            "secondary-type-ids": ["dd2a21e1-0c00-3729-a7a0-de60b84eb5d1"],
            title: "Nirvana",
        },
        {
            title: "With the Lights Out",
            "secondary-type-ids": ["dd2a21e1-0c00-3729-a7a0-de60b84eb5d1"],
            disambiguation: "",
            "first-release-date": "2004-11-23",
            "primary-type": "Album",
            id: "d4d28ec1-220a-327c-93c5-ae006be43598",
            "secondary-types": ["Compilation"],
            "primary-type-id": "f529b476-6e62-324f-b0aa-1f3e33d313fc",
        },
        {
            "first-release-date": "2005-10-31",
            disambiguation: "",
            "primary-type": "Album",
            id: "e9674d41-d94b-344a-89f5-734736853d5f",
            title: "Sliver: The Best of the Box",
            "secondary-type-ids": ["dd2a21e1-0c00-3729-a7a0-de60b84eb5d1"],
            "secondary-types": ["Compilation"],
            "primary-type-id": "f529b476-6e62-324f-b0aa-1f3e33d313fc",
        },
        {
            "first-release-date": "2010-08-31",
            disambiguation: "",
            "primary-type": "Album",
            id: "5cc5dc44-8860-462e-8aa5-2cf9b71af237",
            title: "ICON",
            "secondary-type-ids": ["dd2a21e1-0c00-3729-a7a0-de60b84eb5d1"],
            "primary-type-id": "f529b476-6e62-324f-b0aa-1f3e33d313fc",
            "secondary-types": ["Compilation"],
        },
        {
            "secondary-types": ["Compilation"],
            "primary-type-id": "f529b476-6e62-324f-b0aa-1f3e33d313fc",
            title: "2 for 1: Incesticide / In Utero",
            "secondary-type-ids": ["dd2a21e1-0c00-3729-a7a0-de60b84eb5d1"],
            "primary-type": "Album",
            disambiguation: "",
            "first-release-date": "2011",
            id: "95563c6a-92e5-456c-9f86-6fe2ff1d148e",
        },
        {
            "primary-type-id": "f529b476-6e62-324f-b0aa-1f3e33d313fc",
            "secondary-types": ["Compilation", "Live"],
            id: "55fca0ec-17ed-4860-b700-ef366574aa42",
            disambiguation: "",
            "primary-type": "Album",
            "first-release-date": "1994-11-15",
            "secondary-type-ids": [
                "dd2a21e1-0c00-3729-a7a0-de60b84eb5d1",
                "6fd474e2-6b58-3102-9d17-d6f7eb7da0a0",
            ],
            title: "Live! Tonight! Sold Out!!",
        },
        {
            "secondary-types": ["Compilation", "Live"],
            "primary-type-id": "f529b476-6e62-324f-b0aa-1f3e33d313fc",
            id: "249e7835-5c39-3a10-b15b-e2d3470fb40c",
            disambiguation: "",
            "first-release-date": "1996-09-30",
            "primary-type": "Album",
            "secondary-type-ids": [
                "dd2a21e1-0c00-3729-a7a0-de60b84eb5d1",
                "6fd474e2-6b58-3102-9d17-d6f7eb7da0a0",
            ],
            title: "From the Muddy Banks of the Wishkah",
        },
        {
            "primary-type-id": "f529b476-6e62-324f-b0aa-1f3e33d313fc",
            "secondary-types": ["Live"],
            title: "1991-11-25: Amsterdam 91: Paradiso, Amsterdam, The Netherlands",
            "secondary-type-ids": ["6fd474e2-6b58-3102-9d17-d6f7eb7da0a0"],
            "primary-type": "Album",
            disambiguation: "",
            "first-release-date": "1991-11-25",
            id: "aecb3920-2b8c-3558-a6c5-62bb8d16a95e",
        },
        {
            "secondary-types": ["Live"],
            "primary-type-id": "f529b476-6e62-324f-b0aa-1f3e33d313fc",
            id: "fb3770f6-83fb-32b7-85c4-1f522a92287e",
            disambiguation: "",
            "first-release-date": "1994-10-31",
            "primary-type": "Album",
            "secondary-type-ids": ["6fd474e2-6b58-3102-9d17-d6f7eb7da0a0"],
            title: "MTV Unplugged in New York",
        },
        {
            "secondary-type-ids": ["6fd474e2-6b58-3102-9d17-d6f7eb7da0a0"],
            title: "Live at Reading",
            id: "48f5d526-0fa6-4ca6-ac59-9b2cf9ef464f",
            disambiguation: "",
            "primary-type": "Album",
            "first-release-date": "2009-10-30",
            "primary-type-id": "f529b476-6e62-324f-b0aa-1f3e33d313fc",
            "secondary-types": ["Live"],
        },
        {
            "secondary-types": ["Live"],
            "primary-type-id": "f529b476-6e62-324f-b0aa-1f3e33d313fc",
            id: "e0372c5a-1750-46ec-8f1b-4b76df1fe8e7",
            "primary-type": "Album",
            disambiguation: "",
            "first-release-date": "2011-09-26",
            "secondary-type-ids": ["6fd474e2-6b58-3102-9d17-d6f7eb7da0a0"],
            title: "Live at the Paramount",
        },
        {
            id: "c171986d-83d9-4659-9644-ce9dc2b30836",
            disambiguation: "",
            "first-release-date": "2013-09-23",
            "primary-type": "Album",
            "secondary-type-ids": ["6fd474e2-6b58-3102-9d17-d6f7eb7da0a0"],
            title: "Live and Loud",
            "primary-type-id": "f529b476-6e62-324f-b0aa-1f3e33d313fc",
            "secondary-types": ["Live"],
        },
        {
            title: "Complete Live On KAOS FM 1987",
            "secondary-type-ids": ["6fd474e2-6b58-3102-9d17-d6f7eb7da0a0"],
            "first-release-date": "2015-05-08",
            disambiguation: "",
            "primary-type": "Album",
            id: "603761e1-7d54-41d3-b56b-f012a449f163",
            "secondary-types": ["Live"],
            "primary-type-id": "f529b476-6e62-324f-b0aa-1f3e33d313fc",
        },
        {
            "primary-type": "Single",
            disambiguation: "",
            "first-release-date": "1988-11",
            id: "04f53329-d0d0-3b0d-856a-1e2cbcde0e69",
            title: "Love Buzz",
            "secondary-type-ids": [],
            "secondary-types": [],
            "primary-type-id": "d6038452-8ee0-3f68-affc-2de9a1ede0b9",
        },
        {
            "secondary-types": [],
            "primary-type-id": "d6038452-8ee0-3f68-affc-2de9a1ede0b9",
            disambiguation: "",
            "primary-type": "Single",
            "first-release-date": "1990-09",
            id: "c01d417b-0e34-3723-9ebe-87de4620080c",
            title: "Sliver",
            "secondary-type-ids": [],
        },
        {
            "secondary-types": [],
            "primary-type-id": "d6038452-8ee0-3f68-affc-2de9a1ede0b9",
            title: "Candy / Molly’s Lips",
            "secondary-type-ids": [],
            "primary-type": "Single",
            disambiguation: "",
            "first-release-date": "1991-01",
            id: "8c22577f-aaea-3973-9d27-20731751e088",
        },
        {
            "secondary-types": [],
            "primary-type-id": "d6038452-8ee0-3f68-affc-2de9a1ede0b9",
            id: "40f18565-ab15-3a93-8a9a-4ed6be9a112e",
            disambiguation: "",
            "first-release-date": "1991-06",
            "primary-type": "Single",
            "secondary-type-ids": [],
            title: "Here She Comes Now / Venus in Furs",
        },
        {
            "primary-type-id": "d6038452-8ee0-3f68-affc-2de9a1ede0b9",
            "secondary-types": [],
            "primary-type": "Single",
            disambiguation: "",
            "first-release-date": "1991-09-10",
            id: "03345972-d2f8-36bb-b49a-03a9ceccb7a7",
            title: "Smells Like Teen Spirit",
            "secondary-type-ids": [],
        },
        {
            "primary-type-id": "d6038452-8ee0-3f68-affc-2de9a1ede0b9",
            "secondary-types": [],
            "secondary-type-ids": [],
            title: "Come as You Are",
            id: "6970c348-86ce-3902-bee3-d2ebabc2643d",
            "first-release-date": "1991",
            disambiguation: "",
            "primary-type": "Single",
        },
        {
            id: "be95ba52-8a66-3769-82ad-b5024e993ad7",
            disambiguation: "",
            "first-release-date": "1992-07-20",
            "primary-type": "Single",
            "secondary-type-ids": [],
            title: "Lithium",
            "primary-type-id": "d6038452-8ee0-3f68-affc-2de9a1ede0b9",
            "secondary-types": [],
        },
        {
            id: "5d8050da-e5c9-3a1b-9e39-0a73620218c0",
            "first-release-date": "1992-11-30",
            disambiguation: "",
            "primary-type": "Single",
            "secondary-type-ids": [],
            title: "In Bloom",
            "secondary-types": [],
            "primary-type-id": "d6038452-8ee0-3f68-affc-2de9a1ede0b9",
        },
    ],
    gender: null,
    "end-area": null,
    ipis: [],
    "type-id": "e431f5f6-b5d2-343d-8b36-72607fffb74b",
    isnis: ["0000000123486830", "0000000123487390"],
    "gender-id": null,
    begin_area: {
        "sort-name": "Aberdeen",
        "type-id": null,
        name: "Aberdeen",
        disambiguation: "",
        id: "a640b45c-c173-49b1-8030-973603e895b5",
        type: null,
    },
    end_area: null,
};
